services:
  python:
    container_name: USTMB-Python
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SET_PROXY=1
      - PROXY_HOST=YOUR-PROXY-HOST
      - PROXY_PORT=YOUR-PROXY-PORT
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - TERM_CODE=${TERM_CODE}
    command: ["python","./TelegramBot/main.py"]
    volumes:
      - .:/app
    depends_on:
      - psql
    networks:
      - my-network

  psql:
    container_name: USTMB-Psql
    image: hub.hamdocker.ir/postgres:14.15-alpine3.21
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - my-network

networks:
  my-network:
    driver: bridge